-- completion must load before lsp (capabilities)
require("config.options")
require("config.keymaps")
require("plugins.whichkey")
require("plugins.theme")
require("plugins.lualine")
require("plugins.completion")
require("plugins.lsp")
require("plugins.format")
require("plugins.todo")
require("plugins.telescope")
require("plugins.tmux")
require("plugins.git")
require("plugins.harpoon")
require("plugins.tex")
